[package]
name = "pyrite-config"
version = "0.0.0"
authors = ["Erik Hedvall <hello@erikhedvall.nu>"]
build = "build.rs"

[lib]
name = "pyrite_config"

[dependencies]
anymap = "0.12"
lalrpop-util = "0.18"


[build-dependencies]
lalrpop = {version = "0.18", features = ["lexer"]}
