[package]
name = "pyrite-config"
version = "0.0.0"
authors = ["Erik Hedvall <hello@erikhedvall.nu>"]
build = "build.rs"

[lib]
name = "pyrite_config"

[dependencies]
anymap = "0.11"
lalrpop-util = "0.6"


[build-dependencies]
lalrpop = "0.6"